# Generated by Django 4.0 on 2024-02-25 18:13

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.TextField()),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.UUIDField(editable=False, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=10)),
                ('dinero', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fees_total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fees_pendiente', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fees_cobrado', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('fees_mode', models.CharField(choices=[('A', 'Mode_A'), ('B', 'Mode_B')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainPayment',
            fields=[
                ('datos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trade.datos')),
            ],
            options={
                'verbose_name': 'BlockchainPayment',
                'verbose_name_plural': 'BlockchainPayments',
            },
            bases=('trade.datos',),
        ),
        migrations.CreateModel(
            name='FiatPayment',
            fields=[
                ('datos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trade.datos')),
            ],
            options={
                'verbose_name': 'FiatPayment',
                'verbose_name_plural': 'FiatPayments',
            },
            bases=('trade.datos',),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('datos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trade.datos')),
                ('error', models.BooleanField(default=False)),
                ('error_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Logs',
                'verbose_name_plural': 'Logs',
            },
            bases=('trade.datos',),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('datos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trade.datos')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
            bases=('trade.datos',),
        ),
        migrations.AddField(
            model_name='datos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.usuarios'),
        ),
    ]
